---
name: Functions

on:
  push:
    branches:
      - main
      - ak/deployment/http

permissions:
  contents: read
  id-token: write

jobs:
  http:
    name: ${{ matrix.name }} (HTTP)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - analysis-manager
          - page-cache
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
