---
name: Functions

on:
  push:
    branches:
      - main
      - dev
      - ak/deployment/http

permissions:
  contents: read
  id-token: write

env:
  REGION: us-central1
  RUNTIME: python312

jobs:
  http:
    name: Deploy ${{ matrix.name }} (HTTP)
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref_name }}_${{ matrix.name }}
    strategy:
      matrix:
        name:
          - analysis-manager
          - page-cache
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - uses: google-github-actions/setup-gcloud@v2
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: backend/${{ matrix.name }}/pyproject.toml

      - name: Export requirements
        run: |
          pdm export \
            --project backend/${{ matrix.name }} \
            -f requirements \
            -o backend/${{ matrix.name }}/requirements.txt \
            --without-hashes

      # TODO: require authentication for invocation
      - name: Deploy
        run: |
          gcloud functions deploy ${{ matrix.name }} --gen2 \
            --region=${REGION} \
            --runtime=${RUNTIME} \
            --source backend/${{ matrix.name }} \
            --entry-point=handler \
            --trigger-http \
            --allow-unauthenticated \
            --ignore-file=$(pwd)/.gcloudignore
