---
name: Test

on:
  - push

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version-file: pyproject.toml

      - run: pdm install
      - run: pdm test
